[package]
name = "bevy_reactor_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_mod_stylebuilder = { workspace = true }
bevy_reactor_signals = { workspace = true }
