[package]
name = "obsidian_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
bevy_mod_picking = { workspace = true }
bevy_reactor_signals = { workspace = true }
bevy_reactor = { path = "../.." }
